---

- name: 'INSTALL | APT | Install system dependencies'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: True
    cache_valid_time: "{{ logstash_apt_cache_valid_time }}"
  with_items: "{{ logstash_system_dependencies }}"


- name: 'INSTALL | APT | Install Logstash key'
  apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ logstash_gpg_keys }}"


- name: 'INSTALL | APT | Add Logstash repository'
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state | default('present') }}"
    filename: "{{ item.filename | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  with_items: "{{ logstash_repositories }}"


- name: 'INSTALL | APT | Install Logstash packages'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: True
    cache_valid_time: "{{ logstash_apt_cache_valid_time }}"
  with_items: "{{ logstash_packages }}"
  notify:
    - 'HANDLER | Restart logstash'


- name: 'INSTALL | SERVICE | Manage Logstash service'
  service:
    name: "{{ logstash_service_name }}"
    enabled: "{{ logstash_service_enabled }}"
    state: "{{ logstash_service_state }}"
  notify:
    - 'HANDLER | Restart logstash'
