---

# Main tasks file for logstash role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::logstash'
    - 'role::logstash::init'

- name: 'Load the OS specific varibles'
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"
  tags:
    - 'install'
    - 'logstash'


- include: 'install_debian.yml'
  when: "{{ ansible_os_family == 'Debian' }}"
  tags:
    - 'install'
    - 'logstash'
